### ISSUE TITLE
Unable to load recordings

### ISSUE THREAD

**Issue by AceConrad** [jessedp/tablo-tools-electron#103]
**Describe the bug**
After installing Tablo Tools I see a screen that says "Channels will show up once the db finishes downloading." The channels never show up even after at least 30 minutes. 

**To Reproduce**
1. Go to 'Home Screen'
2. Click on 'Reload under Recordings'
4. See error Problem building...
TypeError: Cannot read property '_id' of null

**Expected behavior**
I expect to see the list of recordings

**Screenshots**

![Screenshot 2021-11-07 093715](https://user-images.githubusercontent.com/93871399/140649529-5baae4e7-a091-430f-afae-6d3c84249605.jpg)

**Environment:**
 - OS:  Win 10
 - App Version  0.2.4

**Additional context**

**Comment by jessedp** [comment]
I just [released a new beta](https://github.com/jessedp/tablo-tools-electron/releases/tag/v0.3.0-beta.3) in case you'd like to give it a shot again and see if this stops happening.
