### ISSUE TITLE
The display compositor is frequently crashing. Goodbye.

### ISSUE THREAD

**Issue by JimShip** [jessedp/tablo-tools-electron#104]
#### Expected Behavior

I expect that tablo-tools should start up and display the main window

#### Current Behavior
When I start tablo-tools the main window pops up then immediately shuts down.  When I start it from a terminal window I get the following error message.

[315354:1107/113138.707312:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
Failed to generate minidump.Illegal instruction (core dumped)

This started when I upgraded my Fedora 34 system to Fedora 35.
Linux laurie.family.net 5.14.16-301.fc35.x86_64 #1 SMP Wed Nov 3 13:55:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5

#### Steps to Reproduce (for bugs)

1.

2.

3.

4.

#### Your Environment

- App version -
- Last 4 of Tablo ServerID -
- Tablo Firmware version -
- Operating System and version -

**Comment by dougK44883** [comment]
Do I understand, you've used Tablo Tools on your system, upgraded/updated your system and now it doesn't? ...it has worked?

Sadly, no I don't have any answers, just wondered that it did work at one time.  I understand Tablo Tools come kind of "pre-bundled" with most of what it needs.  Can just comment, it continues to work on my Linux Debian system, so there should be hope :)

**Comment by JimShip** [comment]
I have used tablo-tools on my system for a very long time with no problems.  The only change to my system was my upgrade from Fedora 34 to 35 and nothing else.
I also tried the appimage version with exactly the same result.

**Comment by JimShip** [comment]
I just tried running tablo-tools as root.  It works fine, after the --no-sandbox option is used.
Maybe a permission or selinux problem since the Fedora 35 upgrade?

**Comment by JimShip** [comment]
Any help for how to troubleshoot this?  I'm running tablo-tools as root --no-sandbox, but that is not ideal.  Since the program won't even start how do I get information about the failure?
Help please.
Jim

**Comment by dougK44883** [comment]
Just tossing things at the wall... check any changelog from 34 > 35 to see "what changed" if you can catch something which may have made the change.

Display compositor, is this your window manager or display manager?   Can you find anything in a system log or journal indicating issues before it went FATAL?

**Comment by jessedp** [comment]
I looked when you first posted this and found nothing ... second time around and I found [this](https://www.reddit.com/r/Fedora/comments/qm3qm1/fedora_35_most_electron_apps_are_not_starting/) which basically says to use the `--disable-seccomp-filter-sandbox` flag (no root) when launching. What that links to says it could be the electron version, so maybe if I ever finish a new version that won't be necessary.

**Comment by dougK44883** [comment]
My Debian Linux run Xorg, no Wayland (it's been upgraded, upgraded... upgraded from before Wayland became default for Debian) and I use Mate Desktop, keeping it "old school" which is likely why I haven't had any issues.
 
If electron is based or built from Chrome or Chromium, there have been several releases releases in the past 2yrs and I'd image electron has had a couple as well.  Not that saying they are all good or necessary...

**Comment by JimShip** [comment]
I just tried the --disable-seccomp-filter-sandbox flag and it worked.  I can use tablo-tools again.  Thanks.
Jim
