### ISSUE TITLE
Invalid time value when listing shows and series

### ISSUE THREAD

**Issue by Anarethos** [jessedp/tablo-tools-electron#108]
Clicking on "Browse Recordings" and then "Shows & Series" and then on any titles, I get the error "RangeError: Invalid time value".

Does not happen for "Movies" section.

#### Expected Behavior

I should be ale to list all current recording for the selected "Shows & Series" selected and not an error.

#### Current Behavior

As described, unable to list the content of the selected show or series in the "Browse Recording\Shows & Series" section.

Works well for "Movies".

Selecting the show or the series from the "Search" section works and I am able to export/delete/manage them.

#### Possible Solution

Not sure .... 

#### Steps to Reproduce (for bugs)

1. Open "Tablo Tools"

2. Click on Browse Recordings

3. Select Shows & Series

4. Click any show or series listed and get the error.

#### Your Environment

- App version - 0.2.4
- Last 4 of Tablo ServerID - 4780
- Tablo Firmware version - 2.2.40
- Operating System and version - Windows 10 21H2, French Canadian
- The "Timezone" filed is empty in the "Current Tablo" window
- I am using a Tablo Quad without HDMI - giv - gen2-4
- Computer/Tablo in the same subnet / No FW between the two
- Connected through Wifi
- Current Windows Time Zone - EAST (Montreal)

#### Full stack trace

RangeError: Invalid time value
    in QB
    in withRouter(QB)
    in h
    in t
    in t
    in ef
    in withRouter(ef)
    in div
    in div
    in cf
    in Unknown
    in t
    in n
    in r
    in h
    in w
    in Unknown
    in i

**Comment by jessedp** [comment]
I believe I finally fixed this in the [just released beta](https://github.com/jessedp/tablo-tools-electron/releases/tag/v0.3.0-beta.3) in case you'd like to give it a shot.

**Comment by Anarethos** [comment]
Seems to work!

**Comment by jessedp** [comment]
Yay. Sorry it took so long!

**Comment by alexandremoore** [comment]
@jessedp I'm having the same error using latest (v0.3.4-beta.1). 
Tablo device: 2.2.42

**Comment by jessedp** [comment]
@alexandremoore I can't replicate the original issue this was for and don't see it happening elsewhere. Please verify the steps to reproduce, try to save the logs to a file/take a screenshot of the errors in Dev Tools (View->Toggle Developer Tools), and open a fresh issue with that info.

**Comment by dougK44883** [comment]
There is no real pattern.  I've seen it occasionally with just any o'l random show via Browse Recordings > Shows and Series.  I can select individual episodes via search.

 Tablo Tools v0.3.4-beta.1
![image](https://user-images.githubusercontent.com/42115699/195689059-eca54d9f-2dda-44ad-9b22-db22d6af8f27.png)

Just one show, just sometimes, different sources (channels)

**Comment by alexandremoore** [comment]
@jessedp I created this PR to address the issue:
https://github.com/jessedp/tablo-tools-electron/pull/131
