### ISSUE TITLE
Export Not Skipping existing files

### ISSUE THREAD

**Issue by ChuckDobbs** [jessedp/tablo-tools-electron#112]
**Describe the bug**
I'm seeing some strange behavior in the export . 

My Assumption is if a show/movie has been exported you can set the export contingent on whether a file with the same name exists in the target directory. i.e., skip, overwrite, or append... This functionality is not working for me. The file simply overwrites the older file on in the target directory in every case. 

I tried exporting a movie a second time directly after. I am, however, seeing export filenames color red and green so it looks like the ap can see the existing files.

**To Reproduce**
1. Set the behavior in Settings/Export to Skip if File exists (or increment. Neither work)
2. Search for a show to export
3. Add a show/movie to the Cart
4. In Cart Select Export
5.  Verify "On Duplicate Dropdown selection of "Skip"
6. Click "Export" button.
7. Once it completes repeat 4 and 5. (export the same file again)

The show will be exported and overwrite the existing file in the target directory

**Expected behavior**
I expected the show with the existing target file to NOT export and move to the next selected show on the export list

**Screenshots**
NA

**Environment:**
 - OS: WIN 10 Pro VM running on a QNAP 723a NAS
 - App Version from the Home screen: 0.2.4 downloaded last week (8/23 ish)
 I was going to spin up and Ubuntu VM to test it in a Linux env.

**Additional context**
The actual exports are very fast and high quality. Manually selecting new shows is a buzz kill. Once i get my existing library exported
The sort by date feature will be helpful. The suggestion of matching on the name without the suffix in not a bad option,

Thanks for any help you can give.

**Comment by jessedp** [comment]
Based on the screenshot in #110 , my best guess is that the network/UNC path is confusing something.

For a couple reasons, I am actually currently working on rewriting a bunch of the app. Assuming I get it done, hopefully I can find and fix whatever is going on.

**Comment by jessedp** [comment]
I believe I fixed this in the [just released beta](https://github.com/jessedp/tablo-tools-electron/releases/tag/v0.3.0-beta.3) in case you'd like to give it a shot.

**Comment by ChuckDobbs** [comment]
I’ll check it out

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
