### ISSUE TITLE
Multiple tablo devices causes confusion

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#12]
Have 2 tablo devices.  clicking discover tablo generally picks tablo1, subsequent clicks are a hitNmiss between tablo1 and tablo2 which I can then refresh DB for which ever is chosen.

I can, via settings, override IP and decide which I want.  But just to see what would happen, I'm still able to click discover... which allows me to flub things up.  (just checking for "idiot proofing" :) )

## Prerequisites

- [ no ] Using yarn
- [tablo-tools_0.1.6_amd64.deb ] Using an up-to-date master branch
- [ no ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ na ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ na ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

should discover just the same tablo each time, or give you the option.  if you check override IP you shouldn't be able to discover

## Current Behavior

see begining

## Possible Solution

attached ``getipinfo`` (edited personal) to gain insight -- hassle attaching, so pasted to end of comment.

## Steps to Reproduce (for bugs)

probably need multiple devices to reproduce

1.

2.

3.

4.

## Context

Minimally affected.  Basic use

huh?

## Your Environment

- Node version : ?
- Version or Branch used : ?
- Operating System and version : Debian 11 Bullseye aka testing

 | mate-desktop 1.24.0
- Link to your project :
```
{"cpes": [{"http": 21480, "public_ip": "XXX.XXX.XXX.XXX", "ssl": 0, "host": "gii", "private_ip": "192.168.0.11", "slip": 21481, "serverid": "SID_000000000000", "inserted": "2018-10-21 17:38:51.322600+00:00", "server_version": "2.2.26rc1910517", "name": "tablo1", "modified": "2020-04-19 12:52:37.470924+00:00", "roku": 0, "board": "gii", "last_seen": "2020-04-19 12:52:37.468440+00:00"}, {"http": 21900, "public_ip": "XXX.XXXX.XXX", "ssl": 0, "host": "gii", "private_ip": "192.168.0.21", "slip": 21901, "serverid": "SID_000000000000", "inserted": "2019-10-24 22:52:32.579047+00:00", "server_version": "2.2.26rc1910518", "name": "tablo2", "modified": "2020-04-19 12:46:42.450780+00:00", "roku": 0, "board": "gii", "last_seen": "2020-04-19 12:46:42.448431+00:00"}], "success": true}
```

**Comment by jessedp** [comment]
I started working on this yesterday and it'll be in the next version which should be out today or tomorrow.

**Comment by jessedp** [comment]
I image you've seen my forum comment. If you'd give beta 1 a shot, that'd be great.

**Comment by jessedp** [comment]
This is completed with v0.1.7. Enjoy!
