### ISSUE TITLE
0.1.10-beta.2 = white screen

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#13]
tablo-tools_0.1.10-beta.2_amd64.deb goes back to the white-screen-of-death   I clicked the build and review... but it just thanked me.  So I retried and just click upload and hoped for the best.

**Comment by jessedp** [comment]
beta3 should fix this problem.

The build/review and upload tool is for sending the data listed there to me in case I really can't reproduce a problem. Build/review just let's you look at what's would be sent in case you're curious (it's also a mini-dump of some device data). Upload builds it and uploads it in one go. It's certainly not a problem to just do it in case.
