### ISSUE TITLE
0.3.5-beta.1 truncates template filename during export

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#137]
**Describe the bug**
AWESOME function has returned from v0.2.4 with template retention between changing defaults and now ability to change template in file editor!!  super big thanks.   Everything looks great.... then decide to actually export

Filenames do not match the template.  Appears to be some pattern what gets passed to ffmpeg - maybe.  All exports have the same "template" when actually export, or passing to ffmpeg.

**To Reproduce**
1. Go to '...' adding show to export, any template aside from basic default episode path - different templates for different show
2. Click on '....' export
3. Scroll down to '....' whatever/where ever you expect to see the files... not there
4. See error -- notice ffmpeg log ``Output #0, mp4, to`` does not match each template

**Expected behavior**
each filename to match the template

**Screenshots**
![Screenshot at 2022-10-21 09-14-35](https://user-images.githubusercontent.com/42115699/197208111-df52af98-761f-4697-8c36-2ba25ea6d9c3.png)
-Selected with this template (from template-naming.db):
    ` {"type":"episode","label":"pbs1","slug":"pbs1","template":"{{episodePath}}/{{lowercase airing_details.channel.channel.network}}/{{pascalcase (strip \" on Masterpiece\" stripShowTitle)}}-{{lPad episode.number}}-{{stripTitle}}.{{EXT}}","_id":"7qihTzisyXsexjtk"}`
-Output name from log:  `Output #0, mp4, to '/media/dvr/VanDerValkOnMasterpiece-Payback in Amsterdam.mp4'`
Concludes with **!Export file does not exist after export**

![image](https://user-images.githubusercontent.com/42115699/197209474-e745230e-40b4-4950-8fc9-c17808883464.png)
-Selected with this template (from template-naming.db):
    ``{"type":"episode","label":"dablTV","slug":"dabltv","template":"/media/dvr/dablTV/{{pascalcase stripShowTitle}}-{{episodeOrDate}}-{{stripTitle}}.{{EXT}}","_id":"cYw715Rg80hIAeaA"}``
-Output name from log: `Output #0, mp4, to '/media/dvr/GeorgeClarkesAmazingSpaces-Railway Carriage and a Victorian Loo.mp4'`

** Oddity ** In the above screenshot, episode 5 was 1 out of 9 which came out as expected ?!?
`Output #0, mp4, to '/media/dvr/dablTV/GeorgeClarkesAmazingSpaces-s10e05-Camping Pod and a Straw Bale House.mp4'`
Same template as above.  Same session as all the other exports with issues.  Only one of nine which seemed to work "right". 

![image](https://user-images.githubusercontent.com/42115699/197210307-16a06fad-a4ea-4ac7-a6fd-1b3cd620bd13.png)
-Selected with this template (from template-naming.db):
```{"type":"episode","label":"archives","slug":"archives","template":"/media/VideoArchives/{{pascalcase (strip \"The \" stripShowTitle)}}/{{seasonNum}}/{{pascalcase (strip \"The \" stripShowTitle)}}-{{episodeOrDate}}-{{stripTitle}}.{{EXT}}","_id":"F8wCRG6MPPZre8Oe"}```
-Output name from log: `Output #0, mp4, to '/media/dvr/MissionImpossible-The Tram.mp4'`

``"episodePath":"/media/dvr"``

**Environment:**
 - OS: [e.g. Win 10]
 - App Version from the Home screen [e.g.0.2.1-beta.1 ]

**Additional context**
I still can't find any "Donate" button.  Tablo-Tools is a beautiful piece of work.  I realize there is an unbelievable amount of time invested.  I'd like to show my appreciation, not just pointing out issues.

**Comment by dougK44883** [comment]
Although you've obviously figured it all out.  It now seems it actually used the last selected template for export despite what was displayed :(

Now it's great - that I can change [default] templates on-the-fly from the file editor each time!  At first I thought maybe I was switching too fast and lost track or forgetting to click the green check.  Sometimes they didn't end up right.  It may have been me, but I retried and seems to be anomalies.  Either I do keep loosing track what I'm doing, or sometimes some seem to change... or things work differently and I need to learn the new version.

Eventually most exports seemed to work out alright.  I do have an extremely odd filename;
``
Output #0, mp4, to '/media/dvr/pbs/{{pascalcase (strip  on Masterpiece stripShowTitle)}}-{{lPad episode.number}}-{{stripTitle}}.{{EXT}}.mp4'
``

1 out of 6.  (I have stopped delete after export)  Just one with the specific template.  
``dj@htpc:/media/dvr/pbs$ ls *.mp4``
``'{{pascalcase (strip  on Masterpiece stripShowTitle)}}-{{lPad episode.number}}-{{stripTitle}}.{{EXT}}.mp4'
``

I know there have been numerous substantial changes since v0.2.0.4  seems everyone else must be getting along so I'm going back and leaving this alone for now.  Other than _annoyances_ I've had little issues with the last working version.  again, THANKS for all the work you've put into this.

**Comment by jessedp** [comment]
As it is now, this is how it _should_ work:

1. Add 1 or more Recordings to the "cart"

2. Visit the Export List:
	A. the current Default Template for each Type of Recording will be locked in place (this issue)
	B. The Filename Editor will allow you to do whatever you want (overriding the "locked" template)
		- setting a different Template _only_ changes it for the current Recording (no other recordings, not the default template)
	C. Maybe Export - go back to Step 1 when complete

3. Use other parts of the app, possibly changing templates

4. Go to Step 1


Nothing that's broken since 0.3.x was necessarily intentional - I was going for it working like 0.2.4. Most things are due to the fact that I had to rewrite the guts of the app - basically anything that touched the filesystem. So exports, any config file updates, usage of the Recording, Show, Templates, etc databases, etc.

I'm going to release this, hope for the best, and will try to spend more time playing with usage patterns that aren't just the simple "add, export" which is likely what most folk do.

**Comment by dougK44883** [comment]
> I was going for it working like 0.2.4. Most things are due to the fact that I had to rewrite the guts of the app - basically anything that touched the filesystem

Thanks, that does give some insight as to the differences (obviously I don't fully understand the intricate details).  If I stick with version, at least for now, I'll not use delete after export.  

I'll wait and tediously confirm things are all in place (not a big problem with OCD).  Then, I believe, I can choose Delete from the cart and remove the shows.  If I feel things are working right, or figure out what I'm doing wrong or what seems to be happening... see what happens or downgrade.

THANKS for all your time and work!
