### ISSUE TITLE
v3.* Deletes file after export

### ISSUE THREAD

**Issue by Fox50LX** [jessedp/tablo-tools-electron#139]
**Describe the bug**

**To Reproduce**
1. Go to 'browse recording'
2. Click on 'export video icon'
3.  open file manager to see export file foldercontents
4. during the export you can see the new filename is created.
5. whne complete the file is gone !!!

**Expected behavior**
should save the file

**Screenshots**

**Environment:**
 - OS: [Win 10 - build 22H2]
 - App Version from the Home screen [all versions past v0.2.4. ]

**Additional context**
[SID_5087B8302A98_Export.zip](https://github.com/jessedp/tablo-tools-electron/files/9844735/SID_5087B8302A98_Export.zip)

**Comment by jessedp** [comment]
- When the export finished, did you click the Log button that appears and see what it says? You can also go to Settings->Advanced to enable debug logging, then look at/post those files (I don't think there's any private info in them, but am not certain right now)

- Did you close the window (not the app) while it was exporting? That will cancel the export process and remove the file.

- Do you have enough disk space? Click the “info” button for the recording to see the approximate size. (as of 0.3.4, there should be disk space warnings displayed)

**Comment by Fox50LX** [comment]
i ran the export (v0.3.4) with logging.  here is the log file,

I dont close (or minimize) the Tablo-Tools application
I do open the file exporer window on top of the Tablo-Tools window
i have over half of my 1TB M.2 as freespace
[1365650-Football Friday-2022-10-22_16-02-44.log](https://github.com/jessedp/tablo-tools-electron/files/9844807/1365650-Football.Friday-2022-10-22_16-02-44.log)

**Comment by Fox50LX** [comment]
here is a screenshot showing the file durring export
![tablo-tool-durring-export](https://user-images.githubusercontent.com/116449752/197350287-128e5f31-79d7-42cb-90d3-106655d8c534.jpg)

**Comment by Fox50LX** [comment]
i dont know if you want to close this but.... i found a fix...do a clean/fresh install.
delete the old install folder
C:\Users\Terry\AppData\Roaming\tablo-tools

re-installed v0.3.4 and it worked

**Comment by Fox50LX** [comment]
here is the log. The file goes away when you close the "Export" box whe complete

![tablo-export-log](https://user-images.githubusercontent.com/116449752/197353121-df5a39c6-e9e8-4724-babc-88e2c00f1cf2.jpg)

**Comment by jessedp** [comment]
Good to hear. The `1365650-Football Friday-2022-10-22_16-02-44.log` you provided above shows that `cancelExportProcess`   happened about 30 seconds after the export had finished, so I'll take a look for weird ways that could accidentally happen.

**Comment by Fox50LX** [comment]
this issue is NOT Fixed.  i thought a fresh/clean install worked, but no.  it still deletes the file wheen you close the completed "Export comple" window
    On Saturday, October 22, 2022 at 01:21:22 PM EDT, jesse ***@***.***> wrote:  
 
 


Closed #139 as completed.

**Comment by dougK44883** [comment]
In the screen shot I noticed they were export a single file via "file editor".  I have confirmed using this method has same results.  Unfortunately Close = Cancel.  The dialog does seem a bit incomplete in the end:

![Screenshot at 2022-10-23 08-03-30](https://user-images.githubusercontent.com/42115699/197391218-e71cbd35-8f16-40b4-854b-ccc19070b33a.png)

Exporting is complete, with [X] Delete when finished? enabled.

It suggest there's a possibility to, again export the deleted recording.  The "how many streams" is pointless here, as well.

I believe removing partially exported files from canceled exports is a feature added to v0.3.x  

It's very unlikely un/installing actually _fixes_ anything.  At best it may go away briefly until you find it's cause.

**Comment by jessedp** [comment]
Sorry for all the emails this caused - 0.3.6 will be out shortly and will fix exports from the popup.

**Comment by dougK44883** [comment]
Level of emails can be set with the un/watch dropdown- 
![image](https://user-images.githubusercontent.com/42115699/197408009-2c17b10c-dfbc-4a4b-bec4-748af9c20d09.png)
Custom, you can only get notified when issues are commented/replied
![image](https://user-images.githubusercontent.com/42115699/197408091-01358067-02f0-420b-8b48-f27e4d994a90.png)

or only when there's a new release, for example.

**Comment by Fox50LX** [comment]
emails are fine.  i got the 0.3.6 update and it did fix my problem.  Thanks so much for the help, and quick fix.  and thanks you for the Awesome application !!!
