### ISSUE TITLE
Auto-Update option doesnt work

### ISSUE THREAD

**Issue by Fox50LX** [jessedp/tablo-tools-electron#140]
**Describe the bug**

**To Reproduce**
1. Go to 'settings'
2. click on 'enable auo-updates' (to uncheck the box, i dont want updates)
3. let it sit for a while
4. click the home screen
5. new version 3.* has been installed

**Expected behavior**
don't auto install new update

**Screenshots**

**Environment:**
 - OS: [e.g. Win 10 build 22H2]
 - App any Version after 0.2.4 ]

**Additional context**
v0.2.4 is the only version that works for me now (new v3.* version delete export file after export.  i have created a seperate issue for that so its frustrating whn it auo-updates

**Comment by dougK44883** [comment]
This may be Windows specific.  I'm using Debian Linux.  I've since downgraded to v0.2.4 several times since v3.x.x and never have had any version change I haven't initiated myself.

Have you read the notes to:
[]Show notification of pre-releases (beta, alpha, etc)?
Notifications will always be shown for full/normal releases that everyone will want. Windows and Linux will **_auto-update._**..

You didn't mention if you've checked this option.

One if for "new releases" the other includes "pre-releases" - notifications for new releases are not optional.

**Comment by Fox50LX** [comment]
No... I haave "Un-Checked that box for auto update and it still updates.  i have also turned off the notiifications
    On Saturday, October 22, 2022 at 07:38:31 PM EDT, Doug K ***@***.***> wrote:  
 
 


This may be Windows specific. I'm using Debian Linux. I've since downgraded to v0.2.4 several times since v3.x.x and never have had any version change I haven't initiated myself.

Have you read the notes to:
[]Show notification of pre-releases (beta, alpha, etc)?
Notifications will always be shown for full/normal releases that everyone will want. Windows and Linux will auto-update...

You didn't mention if you've checked this option.

One if for "new releases" the other includes "pre-releases" - notifications for new releases are not optional.

**Comment by dougK44883** [comment]
>No... I haave "Un-Checked that box for auto update and it still updates.  i have also turned off the notiifications

Sorry, you may find this semantics - trying to be specific for support.  unchecked vs turned off

![image](https://user-images.githubusercontent.com/42115699/197392498-19cabeb2-9879-42b9-ac21-e4b32533f460.png)

I presume by this you have both option un-checked / disabled?

There may be difference between which Windows installation you've chose as well - https://jessedp.github.io/tablo-tools-electron/

> For Automatic Updates:
> 
>     Download the installer for this release - TabloTools-Setup-0.3.4.exe
>     Install TabloTools-Setup-0.3.4.exe
> 
> Updates will happpen the next time the app is opened after a new release is made.
> 
> Other packages:
> 
>     TabloTools-0.3.4.msi
> 
> You will have to check back for new versions on your own. 
> 

Maybe an oversight, the options are just cosmetic.

**Comment by Fox50LX** [comment]
ok, now im confused... are you saying if i install using the *.exe file to install, it will auto-update no matter what?  even if those options are "Un-checked" ?!?!?i have been using the .exe file to install (v0.2.4).  
I had the v0.3.4 installed from the exe fileand... i just got the upgrade to v0.3.6 and... it looks like it fixed my original problem (deleting the export file)
    On Sunday, October 23, 2022 at 08:47:34 AM EDT, Doug K ***@***.***> wrote:  
 
 



No... I haave "Un-Checked that box for auto update and it still updates. i have also turned off the notiifications


Sorry, you may find this semantics - trying to be specific for support. unchecked vs turned off



I presume by this you have both option un-checked / disabled?

There may be difference between which Windows installation you've chose as well - https://jessedp.github.io/tablo-tools-electron/


For Automatic Updates:
Download the installer for this release - TabloTools-Setup-0.3.4.exe
Install TabloTools-Setup-0.3.4.exe

Updates will happpen the next time the app is opened after a new release is made.

Other packages:
TabloTools-0.3.4.msi

You will have to check back for new versions on your own.


Maybe an oversight, the options are just cosmetic.

**Comment by Fox50LX** [comment]
well... looks like this is not a problem.  now that i actually read the instructions... it clearly says on the webpage use the .exe installer for auto-updates.  use the .msi installer for No auto-update.  sorry, my bad.

**Comment by dougK44883** [comment]
It might kind of be a problem... for those who "don't read the instructions".   As you've discovered, there are options which do not work as expected.

  Either they maybe shouldn't be there or the ability to un-check auto-update shouldn't be - it should be permanently checked if that's what it does.

As for the notifications no matter what option, ideally a user should have the option to disable any and all _phone-home_ functions.
