### ISSUE TITLE
Remove selection from export cart

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#147]
**Is your feature request related to a problem? Please describe.**
I have a show in the list and for a variety of reasons - wrong name, maybe - I'd like to easily remove from the list

**Describe the solution you'd like**
A method to remove items from the cart ie) export list individually, quickly and easily from that screen.

**Describe alternatives you've considered**
None.  Only way seems to go back to Browse, TV Shows and find show and find any or all episodes you want to remove - then look at the list and see if you remembered the right one.  Option to use search, similar results

**Additional context**
Just a request, it's "just one of those things" which pop up from time to time...

**Comment by jessedp** [comment]
Using bulk delete on the cart doesn't affect any files you've exported, just the ability to export that recording again since it now no longer exists on the device.

**Comment by dougK44883** [comment]
Yes, I understand - deletes "show" from tablo.  Previously I would enable delete after export.  Now with some changes, I confirm my exports came though as expected (haven't see any issue for several versions) then I bulk delete, after export is complete.

On this note, to remove a show from the export list (thanks!), you use pretty much the same red trashcan as "delete" from table.  It's a bit misleading, hoping it only removes from list.  
   Just suggest is it possible to change, maybe a big red X to to distinguish it from the "delete show" red trashcan.
