### ISSUE TITLE
screwy naming template

### ISSUE THREAD

**Issue by jessedp** [jessedp/tablo-tools-electron#157]
### Discussed in https://github.com/jessedp/tablo-tools-electron/discussions/156

<div type='discussions-op-text'>

<sup>Originally posted by **dougK44883** November 12, 2022</sup>
It seems I have 2 naming templates which result in a file and as the literal template.

```
{"type":"episode","label":"pbs1","slug":"pbs1","template":"{{episodePath}}/{{lowercase airing_details.channel.channel.network}}/{{pascalcase (strip \" on Masterpiece\" stripShowTitle)}}/{{pascalcase (strip \" on Masterpiece\" stripShowTitle)}}-{{lPad episode.number}}-{{stripTitle}}.{{EXT}}","_id":"7qihTzisyXsexjtk"}
{"type":"episode","label":"pbs1a","slug":"pbs1a","template":"{{episodePath}}/{{lowercase airing_details.channel.channel.network}}/{{pascalcase (strip \" on Masterpiece\" stripShowTitle)}}/{{pascalcase (strip \" on Masterpiece\" stripShowTitle)}}-{{lPad episode.number}}.{{EXT}}","_id":"GIhEk3IeKJyKVMBq"}
```
oddly both result in a file name `{{pascalcase (strip  on Masterpiece stripShowTitle)}}-{{lPad episode.number}}-{{stripTitle}}.{{EXT}}.mp4` & `{{pascalcase (strip  on Masterpiece stripShowTitle)}}-{{lPad episode.number}}.{{EXT}}.mp4`
Well, the directory path works out.  From the output log it show ffmpeg outputting to the file, it's not the entire template not getting parsed out.
`Output #0, mp4, to '/media/VideoLibrary/tablo/tbd/Wipeout/{{pascalcase (strip  on Masterpiece stripShowTitle)}}-{{lPad episode.number}}-{{stripTitle}}.{{EXT}}.mp4':`

In the export list it shows the correct filename, no sign or any error.

I have a template with similar compound handlebars which work fine:
```
{"type":"episode","label":"Net-Show-Show-se-Title","slug":"net-show-show-se-title","template":"{{episodePath}}/{{airing_details.channel.channel.call_sign_src}}/{{pascalcase (strip \"The \" stripShowTitle)}}/{{pascalcase (strip \"The \" stripShowTitle)}}-{{episodeOrDate}}-{{stripTitle}}.{{EXT}}","_id":"OW1YHEhT6ZkH7CSd"}
``` 
I haven't fully dug in.  I have tried the offending templates on a mix of different show, same result.  Haven't changed it since v0.2.4 and it's not a regular use one, so if/when it _broke_ is unclear.

Just posting in case something jumps out to anyone else.  Later I'll swap variables and mix things up.  Suggestions? or **reasonable** guesses.</div>

**Comment by dougK44883** [comment]
Ok, at least have a valid file name.  Just not padded with a leading 0.  Not crucial, there would be some PBS programs with show title = episode 1,2,3,etc  for one example.  So I dug out the episode.number need 2 digits when there 10 or more, for correct ordering.

**Comment by jessedp** [comment]
You needed to use this:
`{{lPad episode.number 2}}`

I'm writing more over in #156
