### ISSUE TITLE
v0.3.8-beta.0 Update local db, auto and manual issues

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#163]
**Describe the bug**
Seems there is not update during an export?  Not sure if it just waits until the "next" increment occurs or just not catching up
![image](https://user-images.githubusercontent.com/42115699/202583382-1950a9f9-356a-4e20-acbe-c98fe1260d3a.png)

I use to be able to click on the "last update" icon and innate an update, either it no longer does or it's not working.  Clicking the House (home) and click the blue Reload isn't work (at least after an export).

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: [e.g. Win 10]
 - App Version from the Home screen [e.g.0.2.1-beta.1 ]

**Additional context**

**Comment by jessedp** [comment]
Updating the db has been disabled during exports since 0.2.3. I think I'd need to change some stuff to feel okay about re-enabling that.
