### ISSUE TITLE
Browse or Search: add function to mark bulk shows watch or unwatched

### ISSUE THREAD

**Issue by dmote75** [jessedp/tablo-tools-electron#166]
#### Steps to Reproduce (for bugs)

1.

2.

3.

4.

#### Your Environment

- App version -
- Last 4 of Tablo ServerID -
- Tablo Firmware version -
- Operating System and version -

**Comment by jessedp** [comment]
You'll find this in the just published [0.3.0-beta.0](https://github.com/jessedp/tablo-tools-electron/releases/tag/v0.3.10-beta.0) and subsequent versions.

**Comment by jessedp** [comment]
I should add that they can be toggled individually using the watched/protected icon for each recording:
![watch-protect-1](https://user-images.githubusercontent.com/77744/210004141-90f7ce40-c9e6-4e7c-b3f1-35b68a71aa01.png)

Plus there is a bulk option (`Mark As...` in the above screenshot) that will allow something like this:
![watch-protect-2](https://user-images.githubusercontent.com/77744/210004254-b6b34348-e2c0-4908-ad5a-2a629089d73c.png)
