### ISSUE TITLE
Test Device no longer able to be selected

### ISSUE THREAD

**Issue by steelea567** [jessedp/tablo-tools-electron#167]
**Describe the bug**
No longer able to use TEST DEVICE with an assigned IP address.

**To Reproduce**
1. Go to home
2. Click on Discover
3. Click on use next to test device with an assigned IP
4. Does not change to using test device

1. Click tablo selection drop down at top right of window
2. Select test device
3. Tablo Tools does not change to test device

**Expected behavior**
Tablo Tools should change to use the test device. Appropriate tablo device information should be shown and the ability to discover and manage recording should work.

**Environment:**
 - OS: Windows 10 Pro 21H2
 - App Version v0.3.9

**Additional context**
I have a VPN connection to a remote network with its own tablo. I can ping the gateway of my local network used for the VPN connection, the gateway of the remote network, and the remote tablo. In the previous version I was using (unfortunately unknown although trying to use previous versions did not resolve the issue) Tablo Tools was unable to see the remote tablo without it being specified as a test device then it worked as expected. I have configured a firewall rule disallowing all traffic to and from the system running this instance of tablo tools to talk to the tablo local to my network. When discover is pressed it says no devices are found however it populates the local IP with the IP of my local tablo. I have tried removing and reinstalling tablo tools and deleting all the app data which did not work and even did a fresh windows install which still gives the same results. If I set a static Ip of the remote tablo in Tablo Ripper it can connect just fine so I don't believe this is a network issue.

**Comment by steelea567** [comment]
Ran the 3.10 beta and test device is working as expected.

**Comment by jessedp** [comment]
Apologies for the delay, though happy to hear that build worked as expected. I just published [0.3.10-beta.0](https://github.com/jessedp/tablo-tools-electron/releases/tag/v0.3.10-beta.0) which should work just as well and has other fixes.
