### ISSUE TITLE
Can No Longer Switch Between Different Tablos 

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#173]
**Describe the bug**
Use to be able to switch to second tablo, take care of _business_ then switch back to first tablo.  This function seems flubbed up.
**To Reproduce**

**Expected behavior**
Click Discover OR use drop-down list to select a different tablo
**Screenshots**
![image](https://user-images.githubusercontent.com/42115699/210664937-cd7a10c4-1471-44d3-8861-17480a11813b.png)
Second tablo is selected - yet the dropdown and current are out of sync.
Click discover
![image](https://user-images.githubusercontent.com/42115699/210665125-62137528-30fd-4ed4-956a-3acb2e156ea5.png)
Choose "tablo0"
![image](https://user-images.githubusercontent.com/42115699/210665204-b57d98a4-fb9c-43bb-8a3e-aa8f95451e1e.png)
and you're SOL, seems you'll never be able to use it again.  The drop down is useless.
**Environment:**
 - OS: [e.g. Win 10] Debian 11
 - App Version from the Home screen [e.g.0.2.1-beta.1 ] Tablo Tools v0.3.10-beta.0

**Additional context**
I can edit config.json to regain some control, but this is a real PITA.

**Comment by jessedp** [comment]
This is working okay for me... was this maybe broken in v0.3.10-beta.0 while I was making the test device work again?

**Comment by dougK44883** [comment]
I've install v0.3.10
![image](https://user-images.githubusercontent.com/42115699/213034084-6aaa54ea-7e2a-4345-9d97-c2f25e07203d.png)

Click Rediscover - select tablo0 in a moment, it comes up tablo2 - same with drop-down in upper right.

Restore previous config.json comes up tablo0 if I select Rediscover, I cannot again select tablo0.

Probably a coincidence, response from https://api.tablotv.com/assocserver/getipinfo/ shows tablo2 first.  The IP for tablo2 is in the Enable Test Device - but it is not enabled, unchecked.

**Comment by dougK44883** [comment]
Thanks, this was becoming a PITA.  With each new version, or something, it wanted to change which device and then couldn't change it back..

**Comment by dougK44883** [comment]
This is working again - THANKS [v0.3.12-beta.1]
