### ISSUE TITLE
Ability to edit the title of recoded episodes

### ISSUE THREAD

**Issue by Waldo79** [jessedp/tablo-tools-electron#181]
I have a lot of recordings whose titles need to be corrected. I would like to correct the titles using Tablo Tools.
Is there any way to do that?  The only way I know of is to download the episode to a different disk and modify it there.
#### Steps to Reproduce (for bugs)

1.

2.

3.

4.

#### Your Environment

- App version -
- Last 4 of Tablo ServerID -2.2.42 (Quad Tablo)
- Tablo Firmware version -1.909.227
- Operating System and version -Win 10

**Comment by dougK44883** [comment]
If you don't want to download recordings, I don't believe Tablo Tools - or anything - will edit anything maintained on your tablo device it's self.

**Comment by Waldo79** [comment]
That’s what I was afraid of (I’ve got 835 recordings over ½ of which need their titles corrected.)

I guess only Tablo can incorporate the capability – although that’s highly doubtful since if you set up a recording then go back into change something prior to the recording being made – you can change everything BUT the title, you have to delete the programmed recording and set up a new one in order to change the title.

It seems once writ the title is writ in stone – DUMB!.

**Comment by jessedp** [comment]
Yeah, you'd have to ask them for that functionality, but I wouldn't hold my breath. I believe they group manually recorded Programs by the title (like I do), which could make changing it painful. 

There's an outside chance you can [mess with the database on the harddrive](https://github.com/jessedp/tablo-tools-electron/issues/96#issuecomment-852273373), but you're 1000% on your own and may very well destroy everything doing that...

**Comment by Waldo79** [comment]
Thanks for the info, I had been looking for what the disk structure is like.

If I can successfully change it on the disk I’ll get back to the forum, if not I won’t.

**Comment by dougK44883** [comment]
> There's an outside chance you can [mess with the database on the harddrive](https://github.com/jessedp/tablo-tools-electron/issues/96#issuecomment-852273373), but you're 1000% on your own and may very well destroy everything doing that...

I believe the /db referenced in the graphic in your link is primarily a backup.  Tablo stores all it's usable data internally.  

This db is used to "migrate drive to new tablo".  If you have a fresh device or factory reset your device, if present [/db] it uses this to configure the new device.

Sadly, it's unlikely this is updated regularly other than when the the button it tapped.

**Comment by Waldo79** [comment]
Ok, thanks for the info. Haven’t tried anything Yet, I need to get a 6-8TB hard drive to download all the recordings before trying to hack the Tablo drive.
