### ISSUE TITLE
Switching tablos

### ISSUE THREAD

**Issue by JUser69** [jessedp/tablo-tools-electron#188]
**Describe the bug**
Does not seem to respond to switching tablos. 

**To Reproduce**
 In the pull down, it list different tablos but clicking on a different one does nothing

**Expected behavior**
Switches to a different IP address

**Screenshots**
![image](https://user-images.githubusercontent.com/42041388/220412712-418b945b-1e6f-4e8a-a3f9-3aa160c307bb.png)

**Environment:**
 - OS: Win10 1809
 - App Version: Tablo Tools v0.3.10
 - 
**Additional context**
 I am just guessing that that is what this is supposed to do.  I could not find documentation on it.

**Comment by dougK44883** [comment]
Try updating Tablo Tools versions.  I've found it working in the recent releases.

**Comment by jessedp** [comment]
Indeed I just had to fix it (again) in [0.3.12](https://github.com/jessedp/tablo-tools-electron/releases/tag/v0.3.12)
