### ISSUE TITLE
v0.3.12 not discovering Tablo on LAN

### ISSUE THREAD

**Issue by mightaswel** [jessedp/tablo-tools-electron#197]
The 0.3.12 version of TabloTools does not see my Tablo with firmware 2.2.42 that is on my LAN space 192.168.11.xxx

My Roku does see my Tablo .

I restarted the TabloTools but still nothing.

**Comment by dougK44883** [comment]
Has previous versions?
Do you have an HDMI tablo? or network connected device?
If it's HDMI, do you have an active subscription?
If it is an HDMI, you have have to enter it's IP in the "test device" as it has no _discovery_ and limited streaming device capabilities.

**Comment by mightaswel** [comment]
Interesting , my.tablotv.com did not find my tablo but if i entered in the 
address I got a page that just says "Nuvyyo Tablo Server".

----- Original Message -----
From: jesse ***@***.***>
To: jessedp/tablo-tools-electron ***@***.***>
Cc: mightaswel ***@***.***>,  Author ***@***.***>
Date: Sun, 19 Mar 2023 17:58:23 -0700
Subject: Re: [jessedp/tablo-tools-electron] v0.3.12 not discovering Tablo 
on LAN (Issue #197)

> Are you able to use http://my.tablotv.com/ on the same computer you are 
running TabloTools?
> 
> Could you take a screenshot of the TabloTools error message(s)?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> 
https://github.com/jessedp/tablo-tools-electron/issues/197#issuecomment-1475466540
> You are receiving this because you authored the thread.
> 
> Message ID: 
***@***.***>
>

**Comment by mightaswel** [comment]
previously the older version did work. It did not work today so i tried 
updating the program

Tablo is ethernet cable into the LAN and i have an active subscription 
(grandfathered into the nice schedule,etc plan).

----- Original Message -----
From: Doug K ***@***.***>
To: jessedp/tablo-tools-electron ***@***.***>
Cc: mightaswel ***@***.***>,  Author ***@***.***>
Date: Sun, 19 Mar 2023 18:36:50 -0700
Subject: Re: [jessedp/tablo-tools-electron] v0.3.12 not discovering Tablo 
on LAN (Issue #197)

> Has previous versions?
> Do you have an HDMI tablo? or network connected device?
> If it's HDMI, do you have an active subscription?
> If it is an HDMI, you have have to enter it's IP in the "test device" as 
it has no _discovery_ and limited streaming device capabilities.
> 
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> 
https://github.com/jessedp/tablo-tools-electron/issues/197#issuecomment-1475486690
> You are receiving this because you authored the thread.
> 
> Message ID: 
***@***.***>
>

**Comment by jessedp** [comment]
I'm fairly surprised that TabloTools can't detect your device if you can access it via the IP address directly. You definitely clicked the "Rediscover" button, yes? Ie, you're not solely expecting it to automatically load them... 
![Screenshot from 2023-03-20 10-17-09](https://user-images.githubusercontent.com/77744/226371787-b20bdaf9-e746-4d2f-acf3-cd92ea89ff80.png)

Worst case, since you can access it directly, you should be able to manually enter the IP address under Settings->Advanced->Enable Test Device and you should be able to access it.
![Screenshot from 2023-03-20 10-24-30](https://user-images.githubusercontent.com/77744/226371894-ffb83033-d5b6-4a21-8ea3-12db6e7be46d.png)


Are you using T-mobile Home Internet? Several people who do (including myself) have had intermittent problems find devices via my.tablotv.com . That issue is caused by T-mobile and there's nothing us users can do to fix it. There are some posts about it on the [community forums](https://community.tablotv.com/search?q=t-mobile%20order%3Alatest).

**Comment by dougK44883** [comment]
My limited understanding and/or experience, as with Tablo-Tools, I presume, my.tablotv.com uses 
`https://api.tablotv.com/assocserver/getipinfo/` for pseudo-network discovery.  If your tablo's local (or WAN) IP has changed, there  appears to be nothing to initiate an update.  (I occasionally swap routers around, changing IPs)

Even if you don't believe either of those are the case, query `https://api.tablotv.com/assocserver/getipinfo/` and see if the returned IP matches the IP you used to connect previously.  Note, it returns JSON Firefox will parse it so you can read it.  A tool as httpie will as well, where Google Chrome doesn't - just a block to text to sort through.

**Comment by mightaswel** [comment]
Regular ethernet cable lan.
Okay, so putting the ip address into the 'test' panel worked. Able to 
download and delete the videos. Phew. Good work people!

----- Original Message -----
From: jesse ***@***.***>
To: jessedp/tablo-tools-electron ***@***.***>
Cc: mightaswel ***@***.***>,  Author ***@***.***>
Date: Mon, 20 Mar 2023 07:33:05 -0700
Subject: Re: [jessedp/tablo-tools-electron] v0.3.12 not discovering Tablo 
on LAN (Issue #197)

> I'm fairly surprised that TabloTools can't detect your device if you can 
access it via the IP address directly. You definitely clicked the 
"Rediscover" button, yes? Ie, you're not solely expecting it to 
automatically load them... 

> Worst case, since you can access it directly, you should be able to 
manually enter the IP address under Settings->Advanced->Enable Test 
Device and you should be able to access it.
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> 
https://github.com/jessedp/tablo-tools-electron/issues/197#issuecomment-1476344117
> You are receiving this because you authored the thread.
> 
> Message ID: 
***@***.***>
>
