### ISSUE TITLE
incomplete blanks window

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#2]
## Prerequisites

- [ ] Using yarn
- [X ] Using an up-to-date master branch
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Change view based on filter selection

## Current Behavior

When I click on the incomplete button in the browse tab, the entire window goes blank.  I haven't found a way to recover.  I delete the entire ~/.config/tablo-tools to "reset" and start over.
![incoplete](https://user-images.githubusercontent.com/42115699/73111038-c824cd80-3ed6-11ea-8dfe-565a05238a9d.png)

## Steps to Reproduce (for bugs)

1. effortlessly click the button

2. click through the menu trying to get something to "work"

3. close program - delete config directory

4. start over

## Your Environment

- Node version :
- Version or Branch used : the software doesn't appear to display a version 
- Operating System and version : Debian Bullseye
- Link to your project :

I just found  your project - BEAUTIFUL!  I haven't fully used it, just looking through it... looks awesome! except for the above issue - does it allow for multiple devices?

**Comment by jessedp** [comment]
Did you download one of the pre-built releases (if so, which version) or did you clone and build the repo? I certainly remember that bug previously and I **thought** the released v0.0.5 worked fine _except_ for exporting, which I'm working on.

**Comment by dougK44883** [comment]
I clicked on your _native app installers_  link and downloaded and installed `tablo-tools_0.0.5_amd64.deb`  Again, tablo-tools looks great!  Most 3rd party apps are just for exporting, and are excellent (I use capto along with wrapto) you've greatly polished it with an amazing GUI

 (I greatly appericate the pre-built installers as end users shouldn't have to compile applications)

**Comment by jessedp** [comment]
Give 0.0.6 a try. https://github.com/jessedp/tablo-tools-electron/releases/tag/v0.0.6

It still doesn't fix exporting.

**Comment by dougK44883** [comment]
It may not export, but the UI seem to work - at least basic function.  I haven't dug into it, but there's no issues anymore -- thanks!!
