### ISSUE TITLE
Is Tablo Tools Generation 4 Tablo compatible ? 

### ISSUE THREAD

**Issue by namasteaz** [jessedp/tablo-tools-electron#210]
**Describe the bug**
No Tablos found.  

**Expected behavior**
My other devices find the Tablo, but Tablo tools shows no Tablo found. 

**Environment:**
 MacOS  M2 Processor 
4th Generation Tablo (white)

<img width="1029" alt="Screenshot 2023-10-10 at 2 27 34 PM" src="https://github.com/jessedp/tablo-tools-electron/assets/147559011/3688aff9-1acf-4884-817a-b9eae2d6fc87">

<img width="1014" alt="Screenshot 2023-10-10 at 2 31 31 PM" src="https://github.com/jessedp/tablo-tools-electron/assets/147559011/3b86b873-4abe-468f-801a-52011dbbe4af">

**Comment by Kravimir** [comment]
Unfortunately, the Tablo Gen4 is not compatible with Tablo Tools nor the other 3rd-party Tablo utilities.

Since it can record (limited) streaming content, Tablo's (Nuvyyo's) new parent company (E.W. Scripps) seems to have asked that it not be able to export recordings.

**Comment by 27hectormanuel** [comment]
but it is able to export recordings. I was able to do it manually with ffmpeg or vlc. What is the problem?

**Comment by dougK44883** [comment]
Getting the steaming URL without any reference to the show is a problem.  Can you access or coordinate any DB or JSON data for shows, series, season, episode, titles for any of the recordings?  Movies, sports and manual recordings have different data associated with them.

With what you have, as great as it is (not trying to discount your success), it maybe incorporate it into a script to selectively export recordings.

**Comment by 27hectormanuel** [comment]
You can grab /server/info and recordings/series/episodes from the server. Perhaps add an easy way to generate an authentication ID if thats an issue.

**Comment by bgiesing** [comment]
> You can grab /server/info and recordings/series/episodes from the server.
How did you generate the authentication to even do that?
