### ISSUE TITLE
Tablo shows "No devices found yet, click Discover"

### ISSUE THREAD

**Issue by dru5h** [jessedp/tablo-tools-electron#216]
**Describe the bug**
The app shows "No devices found yet, click Discover." There is a latest generation Tablo connected to my network. 

**To Reproduce**
Open the app on mac os  14.2.1 (23C71) on M1

**Expected behavior**
Connection to Tablo

**Screenshots**
<img width="838" alt="Screenshot 2024-02-04 at 10 22 28 AM" src="https://github.com/jessedp/tablo-tools-electron/assets/61329615/993f100b-4dee-4bd8-870c-20bd69c985c3">

**Environment:**
 - OS: 14.2.1 (23C71) on M1
 - App Version Version 0.3.14 (0.3.14)
 
**Additional context**
All default config on Tablo

**Comment by jessedp** [comment]
4th gen Tablo devices are not supported - #212

**Comment by dru5h** [comment]
Thanks. Is there any way to connect to a 4th gen via API or SSH? I'm just trying to get recordings off device programatically.

**Comment by jessedp** [comment]
Not really, and that appears to be on purpose. I don't own one and don't plan to, so haven't personally poked at one.
There was some discussion in #210 about a few API-like things that still work like they used to - maybe [look at other closed issues](https://github.com/jessedp/tablo-tools-electron/issues?q=is%3Aissue+is%3Aclosed) for ideas.
