### ISSUE TITLE
Tablo Tools v0.3.14 not finding my Tablo TF1284B

### ISSUE THREAD

**Issue by Bigjohn4** [jessedp/tablo-tools-electron#217]
I have just installed Tablo Tools v0.3.14 on Windows 11. It does not find my Tablo. Tablo is Ethernet attached. 
It is seen by Angry IP scanner:
**IP:	192.168.40.220
Ping:	4 ms
Hostname:	t4g4.lan
Ports:	80,443**
I can access it from my Android Phone. 
Tablo is running firmware 2.2.52

**Comment by dougK44883** [comment]
If you happen to have a _newer_ fourth generation tablo... you're SOL.  check out some of the [closed issues](https://github.com/jessedp/tablo-tools-electron/issues?q=is%3Aissue+is%3Aclosed)  here's the sum of it... https://github.com/jessedp/tablo-tools-electron/discussions/212

**Comment by Bigjohn4** [comment]
Anybody working on this, or is a lost cause?
I was planning on adding an external drive, and I think I will loose any recordings when I do that.

**Comment by jessedp** [comment]
Lost cause - see the threads mentioned above...
