### ISSUE TITLE
Tablo 4th Generation not found

### ISSUE THREAD

**Issue by herbweiner** [jessedp/tablo-tools-electron#218]
Tablo 4th Generation (4 tuners) not found.

Mac Mini M4 running Sequoia 15.1.1, connected via Ethernet

Tablo IP is 192.168.88.217
Mac IP is 192.168.88.215

TabloTools reports that No Tablos Found. Clicking Rediscover has no effect.

ping 192.168.88.217
PING 192.168.88.217 (192.168.88.217): 56 data bytes
64 bytes from 192.168.88.217: icmp_seq=0 ttl=64 time=3.981 ms
64 bytes from 192.168.88.217: icmp_seq=1 ttl=64 time=7.700 ms
64 bytes from 192.168.88.217: icmp_seq=2 ttl=64 time=9.054 ms

traceroute 192.168.88.217
traceroute to 192.168.88.217 (192.168.88.217), 64 hops max, 40 byte packets
 1  192.168.88.217 (192.168.88.217)  10.200 ms  5.445 ms  5.424 ms

Tablo is visible to my iPhone and my RoKu

**Comment by dougK44883** [comment]
> Tablo is visible to my iPhone and my RoKu

It's visible on these devices using an official Tablo support app?

unfortunately is the the issue search filter defaults to "open".  If you open it to closed issues -- there are many topics how this doesn't work.  

On Tablo Community Forum topics how is does not work with Tablo-Tools and does not work with Tablo Ripper and will not work with web browser app.  You got a 4th gen tablo - you need official tablo published app - software tablo licenses.

**Comment by herbweiner** [comment]
Thanks, Doug.

It would be nice if jessedp would update the Quick Start section of https://jessedp.github.io/tablo-tools-electron/ to state that Tablo Tools does not support 4th generation Tablo. Then, people would not waste the time downloading and debugging the problem and submitting new issues.

**Comment by dougK44883** [comment]
all that, and then he wouldn't have to keep pointing it out when another comes along asking.  That is reasonably straight forward even add a banner to the readme for the git hub page.

**Comment by jessedp** [comment]
I also updated my [archive of TabloRipper](https://github.com/jessedp/TabloRipper)
