### ISSUE TITLE
Show something useful when not connected to the internet

### ISSUE THREAD

**Issue by probonopd** [jessedp/tablo-tools-electron#28]
**Describe the bug**

**To Reproduce**
1. Be offline
2. Open the app
3. See error: A white page

**Expected behavior**
A clear and concise description of what went wrong, e.g., "You need to connect to the internet in order to use this application."

**Screenshots**

![](https://user-images.githubusercontent.com/2480569/84594279-b79ed080-ae40-11ea-8691-826c429e242c.png)

**Environment:**
 - OS: Ubuntu xenial
 - App Version: Latest AppImage as of today

**Additional context**
https://github.com/AppImage/appimage.github.io/pull/2053

**Comment by dougK44883** [comment]
There are variables at play here.  After initial use, tablo-tools stores IP info ``~/.config/tablo-tools/config.json``.  
I've disconnected from my internet, opened tablo-tools... a couple seconds of blank screen.  Then it populated with info from tablo1 -- there was no access to tablo2  ie, no white-screen-of-death

LiveTV is noticeably slow to start.  After restoring internet, had to rediscover to acknowledge tablo2.

**Comment by probonopd** [comment]
Works for me now. Thank you very much :+1:
