### ISSUE TITLE
Add a context menu for copy/paste

### ISSUE THREAD

**Issue by jessedp** [jessedp/tablo-tools-electron#50]
Electron doesn't provide it, so try something like [electron-context-menu](https://github.com/sindresorhus/electron-context-menu).

**Comment by dougK44883** [comment]
from [electron-context-menu](https://github.com/sindresorhus/electron-context-menu) "``Copy Link`` for links" could someday possible give the tablo URL to the recording ie)
 
    http://tabloIP:8885/recordings/series/episodes/151217
