### ISSUE TITLE
Vague notification settings

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#66]
**Describe the bug**
v0.1.9 introduced 
>This is optional and can be turned off
ADD: Popup when a new version is loaded showing what changed (like where you're likely reading this)
ADD: Preference popup so new stuff isn't forced down people's throats

**To Reproduce**
1. Go to '...' Settings 
2. Click on '....' General

[] Enable automatic updates?
On Linux and Windows, try to automatically download and install new releases. Regardless of this setting, a notification will appear when a new release is available (or based on your choice below).

[] Show notification of pre-releases (beta, alpha, etc)?
Notifications will always be shown for full/normal releases that everyone will want. Windows and Linux will auto-update...

>Preference popup so new stuff isn't forced down people's throats

**Expected behavior**

That implies I can disable this.  The settings suggest there's not way to stop things.

**Screenshots**

When I launched a new installation, it would show "what changed"  I haven't modified those settings and it's no longer showing.  Is being "notified" being informed of "what changed"?  

**Environment:**
 - OS: [e.g. Win 10] Debian 11 Bullseyes
 - App Version from the Home screen [e.g.0.2.1-beta.1 ] v0.2.2-beta.3

**Additional context**

It's  great that you want to keep your user up to date.  You should have some disclaimer, or clear notice that tablo-tools has some form "phone-home" function.  There's some communication with a "3rd party" checking for version updates without user intervention --- this is NOT optional.   Contraindication to "so new stuff isn't forced down people's throats"

**Comment by jessedp** [comment]
This is fine.
