### ISSUE TITLE
Prevent Recording descriptions from scrolling over controls

### ISSUE THREAD

**Issue by jessedp** [jessedp/tablo-tools-electron#71]
**Is your feature request related to a problem? Please describe.**
When clicking the "scroll" to view a Recording's description, the popup description doesn't close until clicked again.

**Describe the solution you'd like**
Close the descriptions automatically somehow. On mouseOut if possible. Maybe a timer. Maybe the next one closes previous ones.

**Comment by dougK44883** [comment]
another suggestion, if/when I click on something else. 

 If it  a feature to have multiple open, they should scroll under the top of the view area (search filters).
