### ISSUE TITLE
Spelling fix

### ISSUE THREAD

**Issue by knutsenm** [jessedp/tablo-tools-electron#74]
https://github.com/jessedp/tablo-tools-electron/blob/163907c02710c1de12e5f20f6263080026eeed3a/app/containers/SettingsPage.js#L74

...should read `Advanced`

**Comment by jessedp** [comment]
Thanks! You won't see it until the next release...

**Comment by knutsenm** [comment]
np; I just began experimenting w/this app over the weekend, looks great so far!
