### ISSUE TITLE
file version naming downgrades in linux  label:Documentation

### ISSUE THREAD

**Issue by dougK44883** [jessedp/tablo-tools-electron#85]
**Describe the bug**

This is screwy and more FYI for anyone encountering this.  When installing a "release" after a "beta" apt package manager warns of a downgrade.  Of course it's not, so I proceed, ignoring warning since I believe I knew what I was doing and suspected why I got the message.

**To Reproduce**
1. Go to '...' ``sudo apt install ./tablo-tools_0.2.3-beta.2_amd64.deb``
2. Click on '....' ``sudo apt install ./tablo-tools_0.2.3_amd64.deb``
4. See error "``warning: downgrading tablo-tools from 0.2.3-beta.2 to 0.2.3``"

**Expected behavior**

no pointless warnings.

**Screenshots**

**Environment:**
 - OS: [e.g. Win 10] Debian
 - App Version from the Home screen [e.g.0.2.1-beta.1 ]

**Additional context**

I don't see it being necessary to change your naming convention.  I tried to confirm this answer, I found some technical gobbledygook some sensible stuff I could follow.   In the end, the way the version is parsed, the - and apha characters are last, but that leave the 1 (beta version) Using some advanced comparing "stuff" the ~ replacing the - makes all the difference.  Just for information....

```
dj@htpc:~/Downloads$ sudo dpkg --compare-versions 0.2.3-beta.2 gt 0.2.3 || echo no
dj@htpc:~/Downloads$ sudo dpkg --compare-versions 0.2.3~beta.2 gt 0.2.3 || echo no
no

dj@htpc:~/Downloads$ sudo dpkg --compare-versions 0.2.3-beta.2 gt 0.2.3 && echo no
no
dj@htpc:~/Downloads$ sudo dpkg --compare-versions 0.2.3~beta.2 gt 0.2.3 && echo no
dj@htpc:~/Downloads$ 

```
note: gt ``>`` greater than comparison.  ``||`` execute "this" if false or fails  ``&&`` execute "this" if true  (the second example responds no, because I should have changed echo yes for illustrative purposes)
I got that from here...  First this starts the discussion, then on the the man[ual] page for some explanation
[https://askubuntu.com/questions/169936/how-to-compare-two-package-version-numbers](https://askubuntu.com/questions/169936/how-to-compare-two-package-version-numbers)
[https://manpages.debian.org/testing/dpkg/dpkg.1.en.html](https://manpages.debian.org/testing/dpkg/dpkg.1.en.html)     ( find --compare-versions)

Some exhaustive explanation about ~ in package versions
[https://unix.stackexchange.com/questions/230911/what-is-the-meaning-of-the-tilde-in-some-debian-openjdk-package-version-string](https://unix.stackexchange.com/questions/230911/what-is-the-meaning-of-the-tilde-in-some-debian-openjdk-package-version-string)

Here's Debian's *technical* doc about package versions naming/numbering, as used in the control file in the .deb
[https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version)

Admiringly I'm on medical leave from work, so yea I had too much time.  Again, I just wanted an FYI in the event some day someone comes along and wonders why they're downgrading their installation.  It's benign and at this point it unlikely any need to change what already makes sense aka humane readable.

**Comment by jessedp** [comment]
I wonder if I mis-labled the beta release being installed here, but "0.2.3~beta.2" *is* a lower version number than 0.2.3.
