### ISSUE TITLE
Recordings wont load

### ISSUE THREAD

**Issue by dmote75** [jessedp/tablo-tools-electron#91]
#### Current Behavior
Program not loading recordings. I click the LOAD button, it goes up to 100%, stays there for awhile, but never loads any recordings. I uninstalled the program and reinstalled, still same issue. Deleted everything in the C:\Users\dmote75\AppData\Local\tablo-tools-updater folder.
When Opening up program for first time after reinstalling, it already has my Tablo listed, I don't have to click on the DISCOVER button.

#### Steps to Reproduce (for bugs)

1.

2.

3.

4.

#### Your Environment

- App version - 0.2.4
- Last 4 of Tablo ServerID - CA06
- Tablo Firmware version - 2.2.30
- Operating System and version - Win10 latest update

**Comment by jessedp** [comment]
The directory to mess with is:
`C:\Users\<Username>\AppData\Roaming\tablo-tools\`

If you don't care about any app settings, nuke it.

If you want to try copying settings back later, only these files are useful.
* config.json
* saved-search.db
* template-naming.db
* export-log.db

**Comment by dmote75** [comment]
Thanks, that worked. I uninstalled using Revo Uninstaller so was surprised it didn't wipe out that folder. Purged it, reinstalled, and it's working great now.
Once again LOVE the program.
David

**Comment by jessedp** [comment]
Great to hear!
