### ISSUE TITLE
It does not look like you have a network connection.  

### ISSUE THREAD

**Issue by deerewright** [jessedp/tablo-tools-electron#95]
**Describe the bug**
When opening Tablo-Tools, I get this error message: 

"Uh-oh! It does not look like you have a network connection. Please check that and re-open this application."

I am connected via wifi to my local network, using Ubuntu 20.04, appimage 0.2.4

**To Reproduce**
Happens on every open.

I wiped the .config, restarted, and still have the same message.

**Expected behavior**

**Screenshots**
![Screenshot from 2021-04-16 10-11-20](https://user-images.githubusercontent.com/3875818/115046722-6961c000-9e9d-11eb-8458-5749539bdc45.png)

**Environment:**
-Ubuntu 20.04
-Appimage 0.2.4

**Additional context**

EDIT: Disregard, simple fix 101.  I just installed a new router yesterday.  All of my Tablo apps seem to work ok, but none of my browsers were able to connect.  Restarted Tablo (First thing I should have tried).  All fixed.

Feel free to delete this bug.

**Comment by jessedp** [comment]
Whoopsie, thanks for the update!
