### ISSUE TITLE
Tablo Tools fails to detect my Tablo Dual HDMI

### ISSUE THREAD

**Issue by Enthusiaster** [jessedp/tablo-tools-electron#96]
When I open Tablo Tools on my MacBook, it says no connection (see attached screen shot) and does not seem to detect my Tablo Dual HDMI for automatic data download, etc. Does anyone know how to fix this problem? The Tablo is definitely connected to my WiFi network, so I don’t understand why Tablo Tools can’t find it.

**Comment by dougK44883** [comment]
Do you have an active guide data subscription?  In order to stream, even in your own house, with an HDMI device you need an active subscription.

**Comment by Enthusiaster** [comment]
Yes, I do have an active guide data subscription. I have been using it
successfully for about two weeks, since I first set up my Tablo Dual HDMI.
The skip commercials option works fine, too. Does your Tablo Tools work
with your Tablo Dual HDMI?

**Comment by jessedp** [comment]
The screenshot didn't seem to make it through - can you add it? 

Is it/this similar to #95 at all?

FWIW, guide subscription status doesn't affect detecting or using the basic/essential features of a Tablo.

**Comment by Enthusiaster** [comment]
Yes. Here’s the screenshot. I couldn’t figure out how to attach it to the
online entry. It’s the same message as in #95.

**Comment by jessedp** [comment]
Does the [my.tablotv.com](http://my.tablotv.com/) app work fine from the macbook?

Have you tried clearing out any [existing config data](https://jessedp.github.io/tablo-tools-electron/#config) before re-launching Tablo Tools just in case?

**Comment by Enthusiaster** [comment]
No, I can’t get the app to work from my iPad. No luck with Safari on my
MacBook, either. I.e., I haven’t been able to access my Tablo with either
device for any purpose. When I talked to Tablo tech support about this
problem this morning, they said the Tablo HDMIs cannot be controlled from
tablets or computers. They said with HDMI Tablos, you can only stream to
other devices with Roku, etc., or certain smart TVs. They said the HDMIs
are new and they couldn’t say anything about third vendor apps like Tablo
Tools but that Tablo Rippers “should” work with the Tablo HDMIs. I have not
tried clearing existing config data. Will the link you sent me so this?
Otherwise, I don’t know how to clear out existing config data. I’ll try
your link now.

**Comment by dougK44883** [comment]
> FWIW, guide subscription status doesn't affect detecting or using the basic/essential features of a Tablo.

You need to read up on the **HDMI** - TV Connected Tablo devices!!!

>Does the my.tablotv.com app work fine from the macbook?

Again, TV connected tablo's are not comparable with the web app though they are known to work with Tablo RIpper... presumably other 3rd party apps [https://community.tablotv.com/t/is-it-april-fool-s-day-new-tablo-dual-hdmi/25207/46?u=djk44883](https://community.tablotv.com/t/is-it-april-fool-s-day-new-tablo-dual-hdmi/25207/46)

**Comment by dougK44883** [comment]
Above all - do you have a subscription to stream from your TV connected HDMI tablo device?!?  You can't get past how to, until it's confirmed you at least have streaming capabilities via an active subscription.
[https://www.tablotv.com/products/tablo-dual-hdmi-ota-dvr/#subscriptions](https://www.tablotv.com/products/tablo-dual-hdmi-ota-dvr/#subscriptions)
"A subscription also enables some of Tablo's cooler features like **in-home streaming** to additional televisions."

If you do... then there may be something to work with, maybe.

**Comment by Enthusiaster** [comment]
I’ll try to figure out how to clear the config data in Tablo Tools. I was
hoping you could confirm that Tablo Tools will work with my HDMI Tablo.
Table Tools seems quite powerful and versatile, but I will also try Tablo
Ripper if I can’t get Tablo Tools to work.

**Comment by Enthusiaster** [comment]
I do have an active guide subscription. This is the only subscription I can
find, aside from the premium subscription, which permits commercial
skipping, and which I also have. I can’t find a separate subscription for
streaming in home. As I understand it, the I subscription i had is
sufficient for streaming to the specific devices Tablo lists, including
Roku and certain Samsung smart TVs.

**Comment by jessedp** [comment]
Thanks for the links @dougK44883

@Enthusiaster sounds like there's nothing this app is going to help you with any time soon :(

Sorry!

**Comment by Enthusiaster** [comment]
I believe you’re right. Tablo has put some interesting constraints on their
newer HDMI models. It also turns out Tablo Ripper is PC, although I found
an entry that says none of the rippers work with the HDMI Tablos. Early on,
I also tried reading the Tablo external hard drive with the MacBook to
manually extract the recorded video files. The MacBook can’t read the
Tablo-formatted hard drive. My other solution is to input the Tablo HDMI
output to a video recorder— Elegato. Will know in about a week if that will
work. Thank you very much for taking the time to help me with this problem.

**Comment by dougK44883** [comment]
>  It also turns out Tablo Ripper is PC, _although_ I found an entry that says none of the rippers work with the HDMI Tablos.

Note: there was a user spamming negatively about the HDMI because their 30day trial expired... and didn't _know_ they needed a subscription to stream.  It may not work, but I'm not sure a user is a valid source.

As for reading the drive, I do know the HDMI does not transcode the video as the network devices.  Not sure if/why they use a different filesystem or if it's encrypted.  It's likely still a Linux based system so it's probably still a native filesystem, I suspect.

So far as I know, there has only been that one post stating the HDMI device works with a 3rd party device.  Whether it was a production model or you need _special_ access is unclear.

**Comment by Enthusiaster** [comment]
Thanks for all the info. I may look into the Linux idea.

**Comment by jessedp** [comment]
> Thanks for all the info. I may look into the Linux idea.

The drive is probably formatted as **ext4** like the "old" Tablos - [here are some options for mounting ext4 volumes on a Mac](https://www.maketecheasier.com/mount-access-ext4-partition-mac/).

If not, running `diskutil list` or `diskutil info -all` should identify it and basically the same steps in the linked article would apply.

When you get it mounted, it'll look something like this:

![Screenshot from 2021-06-01 12-05-03](https://user-images.githubusercontent.com/77744/120356859-c8a35480-c2d2-11eb-8584-3a4ea4af0f27.png)

The **16102** directory is for a single recording and is just a sequential Id - it has no relation to what you recorded. You'll either need to be able to use the `.ts` files directly or combine them into a single file using some other video tool.

If you can't guess or don't want to hunt and peck to find the recordings, things get much messier - you need to look at their sqlite database in the `db/Tablo.db` which requires circumventing permissions (just use `sudo`) and browsing/searching the `Recording` table using SQL.

**Comment by Enthusiaster** [comment]
Wow! Thank you very much!

**Comment by dougK44883** [comment]
ok, now that we are off Tablo-Tools...  It's unclear the `/db/Tablo.db` is routinely updated.  Following the instructions [Moving your recordings to a new Tablo](https://support.tablotv.com/hc/en-us/articles/213345486-Moving-your-recordings-to-a-new-Tablo) - tap the blue button the reboot your tablo.  Of course, this may/not work on TV connected tablos.

There's a script for reading `/db/Tablo.db`[Extracting Videos from Tablo External Hard Drive]( https://community.tablotv.com/t/extracting-videos-from-tablo-external-hard-drive/25737)  I have no personal experience, although another user has some success with it.

If the TV connected tablo does have a `XXXXX/segs/*.ts`  files, there's information to use handbrake to "recover" recordings - [Recovering Show from good drive/dead tablo](https://community.tablotv.com/t/recovering-show-from-good-drive-dead-tablo/23266)

Again, all these have been tried and tested on an networked tablo.  Whether or not the HDMI TV connected tablo's have the same structure is unknown to me... and many others.  We do know it does not transcode media, yet has some methodology to stream.  
So how it stores --
> Raw MPEG2 Video
> As a TV-connected OTA DVR, Tablo DUAL HDMI records and displays Over-the-Air TV in raw MPEG2 video format at the resolution and bitrate in which it is broadcast, including 1080i @30fps and 720p @60fps, where available. 

-- you may not have segs to reassemble, no idea.

**Comment by Enthusiaster** [comment]
So kind of you to share your exceptional expertise like this. You have
covered all the bases. I will try to make good use of this info. Thanks
again.
